apiVersion: v2
name: duniversity-college-portal
description: A Helm chart for deploying the Duniversity College Portal application
type: application
version: 1.1.0 #It is chart version
appVersion: "1.1.0" #It is the version of the application being deployed
