apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: db
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb   # must match template labels
  serviceName: "mariadb"
  replicas: 3
  minReadySeconds: 10

  template:
    metadata:
      labels:
        app: mariadb   # must match selector
    spec:
      terminationGracePeriodSeconds: 10

      containers:
      - name: mariadb
        image: mariadb:10.5

        ports:
        - containerPort: 3306
          name: db

        envFrom:
          - configMapRef:
              name: col-cfg

        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        - name: schema-volume
          mountPath: /docker-entrypoint-initdb.d/

      volumes:
      - name: schema-volume  
        configMap:
          name: mariadb-schema

  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-csi-storage"
      resources:
        requests:
          storage: 500Mi